# Pipeline entry point. Run `make help` for targets.

SHELL := /bin/bash
.DEFAULT_GOAL := help

-include .env
export

PSQL := docker compose exec -T db psql -v ON_ERROR_STOP=1 -U $${POSTGRES_USER:-hgv} -d $${POSTGRES_DB:-hgv}
PY   := uv run python
# Satellite step used by `make all`: gee-from-csv loads the committed Earth Engine results and
# needs no account; `make all SATELLITE=gee` recomputes them (Earth Engine credentials, ~75 min).
SATELLITE ?= gee-from-csv

.PHONY: help setup env db-up db-check db-down db-reset download inspect load allocation dasymetric osm accessibility ee-check gee gee-from-csv indicators analysis maps dictionary all check reproduced clean

help: ## List targets
	@grep -hE '^[a-z-]+:.*## ' $(MAKEFILE_LIST) | awk -F':.*## ' '{printf "  %-14s %s\n", $$1, $$2}'

env: ## Create .env from .env.example if missing
	@test -f .env || (cp .env.example .env && echo "Created .env")

setup: env ## Install the pinned Python environment
	uv sync --locked

db-up: env ## Start PostGIS and wait until healthy
	docker compose up -d --wait db

db-check: db-up ## Verify PostgreSQL and PostGIS versions
	$(PSQL) -c "SELECT version();" \
	        -c "SELECT extname, extversion FROM pg_extension WHERE extname LIKE 'postgis%' ORDER BY 1;" \
	        -c "SELECT postgis_full_version();"

db-down: ## Stop PostGIS (data volume kept)
	docker compose down

db-reset: ## Stop PostGIS and delete its data volume
	docker compose down -v

download: ## Phase 1: fetch institutional sources into data/raw with a manifest
	$(PY) src/download.py

inspect: download ## Phase 1: inspect raw sources, write docs/validation_report.md
	$(PY) src/inspect_raw.py

load: db-up inspect ## Phase 2: load sources into PostGIS, build clean tables, run checks
	$(PY) src/load_postgis.py

allocation: load ## Phase 2: allocate postal votes to station districts (methods A, B, C)
	$(PY) src/run_sql.py allocation

dasymetric: load ## Phase 2: residential population and land per station district
	$(PY) src/run_sql.py dasymetric

osm: db-up download ## Phase 2: extract OSM amenities into PostGIS
	$(PY) src/osm_extract.py

accessibility: dasymetric osm ## Phase 2: residents within reach of amenities per district
	$(PY) src/run_sql.py accessibility

ee-check: ## Phase 3: verify Earth Engine credentials with a small test query
	$(PY) src/ee_auth.py

gee: dasymetric ## Phase 3: Earth Engine composites and zonal statistics (needs EE credentials)
	$(PY) src/gee_extract.py
	$(PY) src/run_sql.py satellite

gee-from-csv: dasymetric ## Phase 3 without Earth Engine: load the committed data/processed/ee_zonal.csv
	$(PY) src/gee_extract.py --from-csv
	$(PY) src/run_sql.py satellite

indicators: allocation accessibility $(SATELLITE) ## Phase 4: one analysis table per district
	$(PY) src/run_sql.py indicators

analysis: indicators ## Phase 4: correlations (tiers 1 to 3), Moran's I, docs/results.md
	$(PY) src/analysis.py

maps: analysis ## Phase 5: publication maps, PNG (300 dpi) and SVG in figures/
	$(PY) src/maps.py

dictionary: analysis ## Phase 5: validate datapackage.json, render docs/data_dictionary.md
	$(PY) src/data_dictionary.py

all: maps dictionary ## Run the full pipeline

check: ## Static checks: lint, formatting, parameters, data package, citation metadata
	uv run ruff check .
	uv run ruff format --check .
	$(PY) -c "import yaml; yaml.safe_load(open('config/params.yaml'))"
	uv run frictionless validate datapackage.json
	uv run --with cffconvert==2.0.0 cffconvert --validate -i CITATION.cff

reproduced: ## After `make all`: fail if any committed output changed beyond timestamp lines
	@changed=$$(git diff -U0 --no-color | grep -E '^[-+]' | grep -vE '^(\+\+\+|---) ' \
		| grep -v 'Generated by' || true); \
	binary=$$(git diff --numstat | awk '$$1 == "-" {print $$3}'); \
	untracked=$$(git status --porcelain --untracked-files=all | awk '$$1 == "??" {print $$2}'); \
	if [ -n "$$changed$$binary$$untracked" ]; then \
		echo "Outputs differ from the committed versions:"; git status --short; exit 1; \
	fi; \
	echo "All committed outputs reproduced (only timestamp lines differ)."

clean: ## Remove regenerated data (raw and interim)
	find data/raw data/interim -mindepth 1 ! -name .gitkeep -delete
