"""Validate datapackage.json against the committed tables and render docs/data_dictionary.md.

datapackage.json (Frictionless Data) is the single source for column names, types, units,
definitions and sources; the Markdown dictionary is generated from it so the two never diverge.

Usage: uv run python src/data_dictionary.py
"""

from __future__ import annotations

import json
import sys
from pathlib import Path

from frictionless import Package

ROOT = Path(__file__).resolve().parents[1]
DESCRIPTOR = ROOT / "datapackage.json"
OUT = ROOT / "docs/data_dictionary.md"


def cell(text: object) -> str:
    return str(text).replace("|", "\\|").replace("\n", " ")


def main() -> int:
    report = Package(str(DESCRIPTOR), basepath=str(ROOT)).validate()
    if not report.valid:
        for task in report.tasks:
            for err in task.errors[:5]:
                print(f"FAIL  {task.name}: {err.message}", file=sys.stderr)
        return 1
    print(f"valid {DESCRIPTOR.name}: {len(report.tasks)} resources")

    pkg = json.loads(DESCRIPTOR.read_text(encoding="utf-8"))
    lines = [
        "# Data dictionary",
        "",
        f"Generated by `src/data_dictionary.py` from `datapackage.json` (version "
        f"{pkg['version']}), which is validated against the files on every run. "
        "It describes every committed output table. In PostGIS the same columns live in the "
        "tables named in each description; districts are keyed by `uwb` throughout.",
        "",
        f"Licence of the derived tables: {pkg['licenses'][0]['title']}. Sources and their "
        "licences are listed in `docs/provenance.md`.",
    ]
    for res in pkg["resources"]:
        lines += ["", f"## `{res['path']}`", "", res["description"]]
        schema = res.get("schema")
        if not schema:
            continue
        lines += [
            "",
            f"Primary key: {', '.join(f'`{k}`' for k in schema['primaryKey'])}.",
            "",
            "| Column | Type | Unit | Definition | Source |",
            "| --- | --- | --- | --- | --- |",
        ]
        for f in schema["fields"]:
            enum = f.get("constraints", {}).get("enum")
            definition = f["description"] + (
                f" Values: {', '.join(f'`{v}`' for v in enum)}." if enum else ""
            )
            lines.append(
                f"| `{f['name']}` | {f['type']} | {cell(f.get('unit', ''))} | {cell(definition)} "
                f"| {cell(f.get('source', ''))} |"
            )
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
