"""Inspect raw sources and write the Phase 1 section of docs/validation_report.md.

Checks: schemas, keys, row counts, CRS and encodings; station + postal votes against the official
Berlin-wide row; key agreement between results and district geometries; geometry validity,
overlaps and gaps. Every number in the report is computed here from data/raw.

Usage: uv run python src/inspect_raw.py
"""

from __future__ import annotations

import csv
import sys
import zipfile
from datetime import UTC, datetime
from pathlib import Path

import geopandas as gpd
import pandas as pd
import pyogrio
import yaml
from shapely.geometry import Polygon

ROOT = Path(__file__).resolve().parents[1]
REPORT = ROOT / "docs/validation_report.md"
TOTAL_COLS = ["WberIns", "Waehler", "Gueltig", "Unguelt"]


def read_results(path: Path) -> pd.DataFrame:
    return pd.read_csv(path, sep=";", encoding="utf-8-sig", dtype=str)


def party_names(dsb_path: Path) -> dict[str, str]:
    """Party code to name, from the dataset description (ISO-8859-1, `field;description`)."""
    names = {}
    with dsb_path.open(encoding="latin-1", newline="") as f:
        for row in csv.reader(f, delimiter=";"):
            if len(row) >= 2 and row[0][:1] == "P" and row[0][1:].isdigit():
                names[row[0]] = row[1].strip()
    return names


def dsb_field(dsb_path: Path, key: str) -> str:
    with dsb_path.open(encoding="latin-1", newline="") as f:
        for row in csv.reader(f, delimiter=";"):
            if row and row[0].strip() == key:
                return row[1].strip()
    return ""


def md_table(df: pd.DataFrame) -> str:
    cols = list(df.columns)
    lines = ["| " + " | ".join(cols) + " |", "|" + " --- |" * len(cols)]
    lines += ["| " + " | ".join(str(v) for v in row) + " |" for row in df.itertuples(index=False)]
    return "\n".join(lines)


def fmt(n: float) -> str:
    return f"{int(n):,}"


def main() -> int:
    params = yaml.safe_load((ROOT / "config/params.yaml").read_text(encoding="utf-8"))
    raw = ROOT / params["paths"]["raw"]
    er, dg, pdn = raw / "election_results", raw / "district_geometries", raw / "population_density"
    out: list[str] = []
    ok = True

    def check(label: str, passed: bool, detail: str = "") -> None:
        nonlocal ok
        ok &= passed
        out.append(f"| {label} | {'pass' if passed else 'FAIL'} | {detail} |")

    # Results, polling-district level
    w = read_results(er / "Datenexport_AGH2026_Zweitstimme_W_BE.csv")
    a = read_results(er / "Datenexport_AGH2026_Zweitstimme_A_BE.csv")
    dsb_w = er / "DSB_Datenexport_AGH2026_Zweitstimme_W_BE.csv"
    names = party_names(dsb_w)
    pcols = [c for c in w.columns if c in names]
    num = TOTAL_COLS + pcols
    w[num] = w[num].apply(pd.to_numeric)
    stn, pst = w[w.WBezArt == "W"].copy(), w[w.WBezArt == "B"].copy()
    berlin = a[a.Gebietsart == "Bundesland"]
    contested = [c for c in pcols if w[c].sum() > 0]

    # Geometries
    zpath = dg / "RBS_OD_UWB_AH26.zip"
    g = gpd.read_file(f"zip://{zpath}")
    cpg = zipfile.ZipFile(zpath).read("RBS_OD_UWB_AH26.cpg").decode().strip()

    # Population blocks (schema only; full load happens in Phase 2)
    pinfo = pyogrio.read_info(pdn / "ua_einwohnerdichte_2025.gml")

    out += [
        "## Phase 1: raw sources",
        "",
        f"Generated by `src/inspect_raw.py` on {datetime.now(UTC):%Y-%m-%d %H:%M} UTC from the "
        "files listed in `data/raw/manifest.csv`.",
        "",
        "### Sources at a glance",
        "",
    ]
    out.append(
        md_table(
            pd.DataFrame(
                [
                    [
                        "Zweitstimme by polling district (W table)",
                        "CSV, UTF-8 with BOM, `;`",
                        fmt(len(w)),
                        "`Bezirk`+`Wahlbezirk` (W rows); `Briefwahlbezirk` (B rows)",
                        "none",
                    ],
                    [
                        "Zweitstimme by aggregate (A table)",
                        "CSV, UTF-8 with BOM, `;`",
                        fmt(len(a)),
                        "`Adresse`",
                        "none",
                    ],
                    [
                        "Polling district geometries",
                        f"Shapefile, {cpg}",
                        fmt(len(g)),
                        "`UWB`",
                        f"EPSG:{g.crs.to_epsg()}",
                    ],
                    [
                        "Population blocks 2025",
                        "WFS GML 3.2",
                        fmt(pinfo["features"]),
                        "`schluessel`",
                        str(pinfo["crs"]),
                    ],
                ],
                columns=["Source", "Format", "Rows", "Key", "CRS"],
            )
        )
    )
    out += [
        "",
        f'Results status: "{dsb_field(dsb_w, "Inhalt der Daten")}". Extract timestamps '
        f"(`Datum` `Zeit`, format JJ.MM.TT) range from {w.Datum.min()} {w.Zeit.min()} to "
        f"{w.Datum.max()} {w.Zeit.max()} in the W table; the Berlin row in the A table is "
        f"{berlin.Datum.iloc[0]} {berlin.Zeit.iloc[0]}. These are preliminary results; rerun the "
        "pipeline if final results are published.",
        "",
        f"Geometry fields: {', '.join(c for c in g.columns if c != 'geometry')}. "
        f"Population fields (first 8): {', '.join(list(pinfo['fields'])[:8])}.",
        "",
        "### Checks",
        "",
        "| Check | Result | Detail |",
        "| --- | --- | --- |",
    ]

    # Keys and structure
    check(
        "W table: polling-district key unique",
        not stn[["Bezirk", "Wahlbezirk"]].duplicated().any(),
        f"{fmt(len(stn))} station rows",
    )
    check(
        "W table: postal-district key unique",
        not pst.Briefwahlbezirk.duplicated().any(),
        f"{fmt(len(pst))} postal rows",
    )
    unmatched = set(stn.Briefwahlbezirk) ^ set(pst.Briefwahlbezirk)
    per_bwb = stn.groupby("Briefwahlbezirk").size()
    check(
        "Every station row maps to one postal row and vice versa",
        not unmatched,
        f"stations per postal district: min {per_bwb.min()}, median {per_bwb.median():g}, "
        f"max {per_bwb.max()}",
    )
    check(
        "Party votes sum to valid votes in every row",
        bool((w[pcols].sum(axis=1) == w.Gueltig).all()),
        f"{len(contested)} parties with votes",
    )
    check(
        "Eligible voters only on station rows",
        bool((pst.WberIns == 0).all() and (stn.WberIns > 0).all()),
        "postal rows carry `WberIns` = 0, so turnout is computed after allocation",
    )

    # Reconciliation with the official Berlin row
    berlin_vals = berlin.iloc[0][num].apply(pd.to_numeric)
    sums = w[num].sum()
    diffs = {c: int(sums[c] - berlin_vals[c]) for c in num if sums[c] != berlin_vals[c]}
    check(
        "Station + postal totals equal official Berlin row (all columns)",
        not diffs,
        "differences: " + (str(diffs) if diffs else "none"),
    )
    check(
        "All districts reported",
        berlin.AnzWbez.iloc[0] == berlin.AusWbez.iloc[0],
        f"{berlin.AusWbez.iloc[0]} of {berlin.AnzWbez.iloc[0]}",
    )

    # Results to geometries
    stn_keys = stn.assign(UWB=stn.Bezirk + stn.Wahlbezirk)
    m = g.merge(stn_keys[["UWB", "Briefwahlbezirk"]], on="UWB", how="outer", indicator=True)
    both = int((m._merge == "both").sum())
    check(
        "Geometry `UWB` = results `Bezirk`+`Wahlbezirk`, 1:1",
        both == len(g) == len(stn),
        f"{both} matched, {int((m._merge == 'left_only').sum())} geometry only, "
        f"{int((m._merge == 'right_only').sum())} results only",
    )
    check(
        "Geometry `BWB` = results `Briefwahlbezirk`",
        bool((m.BWB == m.Briefwahlbezirk).all()),
        "postal district assignment agrees",
    )

    # Geometry quality
    check(
        "Geometries valid and non-empty",
        bool(g.is_valid.all() and not g.is_empty.any()),
        f"types: {g.geom_type.value_counts().to_dict()}",
    )
    gg = g[["UWB", "geometry"]]
    ov = gpd.overlay(gg, gg.rename(columns={"UWB": "U2"}), how="intersection", keep_geom_type=True)
    ov = ov[ov.UWB < ov.U2]
    check(
        "No overlaps between districts (> 1 m²)",
        not (ov.area > 1).any(),
        f"max overlap {ov.area.max() if len(ov) else 0:.2f} m²",
    )
    union = g.union_all()
    parts = list(getattr(union, "geoms", [union]))
    holes = [Polygon(r).area for p in parts for r in p.interiors]
    check(
        "Coverage has no gaps (> 1 m²)",
        all(h < 1 for h in holes),
        f"{len(parts)} part(s), {len(holes)} sliver holes, largest {max(holes, default=0):.3f} "
        f"m²; total area {g.area.sum() / 1e6:.2f} km²",
    )

    # Party totals
    tot = (
        pd.DataFrame(
            {
                "Code": contested,
                "Party": [names[c] for c in contested],
                "Station": [stn[c].sum() for c in contested],
                "Postal": [pst[c].sum() for c in contested],
            }
        )
        .assign(Total=lambda d: d.Station + d.Postal)
        .assign(Share=lambda d: (100 * d.Total / w.Gueltig.sum()).round(2))
        .sort_values("Total", ascending=False)
    )
    for c in ["Station", "Postal", "Total"]:
        tot[c] = tot[c].map(fmt)
    out += [
        "",
        "### Valid Zweitstimmen by party, Berlin",
        "",
        f"Valid votes {fmt(w.Gueltig.sum())} (station {fmt(stn.Gueltig.sum())}, postal "
        f"{fmt(pst.Gueltig.sum())}). Voters {fmt(w.Waehler.sum())} of {fmt(w.WberIns.sum())} "
        f"eligible, turnout {100 * w.Waehler.sum() / w.WberIns.sum():.1f} %.",
        "",
        md_table(tot.rename(columns={"Share": "Share %"})),
        "",
    ]

    # Keep any later-phase sections already in the report
    text = "\n".join(out)
    if REPORT.exists():
        old = REPORT.read_text(encoding="utf-8")
        rest = old.split("## Phase 2", 1)
        if len(rest) == 2:
            text += "\n## Phase 2" + rest[1]
    REPORT.write_text("# Validation report\n\n" + text.rstrip() + "\n", encoding="utf-8")
    print(f"Wrote {REPORT.relative_to(ROOT)}: {'all checks pass' if ok else 'CHECKS FAILED'}")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
