"""Run one pipeline SQL file and copy its checks into docs/validation_report.md.

Each analysis SQL file builds its tables and a check table with columns (name, passed, detail).
Parameters from config/params.yaml are passed as session settings (`SET hgv.<name>`), which the
SQL reads with current_setting('hgv.<name>'). The run fails if any check fails.

Usage: uv run python src/run_sql.py STEP
  STEP is one of the keys of STEPS below.
"""

from __future__ import annotations

import argparse
import os
import sys
from pathlib import Path

import psycopg
import yaml

ROOT = Path(__file__).resolve().parents[1]
SQL = ROOT / "sql"
REPORT = ROOT / "docs/validation_report.md"

# step: (sql file, check table, report section, params.yaml section passed as settings)
STEPS = {
    "allocation": (
        "20_postal_allocation.sql",
        "analysis.allocation_check",
        "## Phase 2b: postal vote allocation",
        None,
    ),
    "dasymetric": (
        "30_dasymetric.sql",
        "analysis.dasymetric_check",
        "## Phase 2c: dasymetric population",
        "dasymetric",
    ),
}


def dsn() -> str:
    e = os.environ.get
    return (
        f"postgresql://{e('POSTGRES_USER', 'hgv')}:{e('POSTGRES_PASSWORD', 'hgv')}"
        f"@{e('POSTGRES_HOST', 'localhost')}:{e('POSTGRES_PORT', '5432')}/{e('POSTGRES_DB', 'hgv')}"
    )


def write_report(section_title: str, source: str, rows: list[tuple]) -> bool:
    """Replace (or append) one section of the validation report. Return True if all passed."""
    ok = all(r[1] for r in rows)
    lines = [
        section_title,
        "",
        f"Generated by {source}.",
        "",
        "| Check | Result | Detail |",
        "| --- | --- | --- |",
    ]
    lines += [f"| {n} | {'pass' if p else 'FAIL'} | {d} |" for n, p, d in rows]
    section = "\n".join(lines) + "\n"

    text = REPORT.read_text(encoding="utf-8") if REPORT.exists() else "# Validation report\n"
    if section_title in text:
        before, after = text.split(section_title, 1)
        nxt = after.find("\n## ")
        text = before + section + (after[nxt + 1 :] if nxt >= 0 else "")
    else:
        text = text.rstrip() + "\n\n" + section
    REPORT.write_text(text, encoding="utf-8")
    return ok


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("step", choices=STEPS)
    args = parser.parse_args()
    sql_file, check_table, section, param_key = STEPS[args.step]

    params = yaml.safe_load((ROOT / "config/params.yaml").read_text(encoding="utf-8"))
    settings = params.get(param_key, {}) if param_key else {}

    with psycopg.connect(dsn()) as conn:
        for name, value in settings.items():
            # set_config is parameterised; SET does not accept bind parameters.
            conn.execute("SELECT set_config(%s, %s, false)", (f"hgv.{name}", str(value)))
            print(f"set   hgv.{name} = {value}")
        print(f"sql   {sql_file}")
        conn.execute((SQL / sql_file).read_text(encoding="utf-8"))
        conn.commit()
        rows = conn.execute(
            f"SELECT name, passed, detail FROM {check_table} ORDER BY check_id"
        ).fetchall()

    for name, passed, detail in rows:
        print(f"{'pass' if passed else 'FAIL'}  {name}: {detail}")
    source = f"`src/run_sql.py {args.step}` from `{check_table}` (`sql/{sql_file}`)"
    ok = write_report(section, source, rows)
    print(f"Wrote {REPORT.relative_to(ROOT)}: {'all checks pass' if ok else 'CHECKS FAILED'}")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
